# Simple pre-commit config for version bumping only
repos:
  - repo: local
    hooks:
      - id: bump-version
        name: Bump Version
        entry: py -m scripts.pre_commit_bump
        args: [patch]
        language: system
        pass_filenames: false
