name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}

      - name: Add Oracle instance to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.ORACLE_HOST_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Oracle Cloud
        run: |
          ssh ubuntu@${{ secrets.ORACLE_HOST_IP }} "mkdir -p ~/deployment-temp"
          scp -r ./* ubuntu@${{ secrets.ORACLE_HOST_IP }}:~/deployment-temp/
          ssh ubuntu@${{ secrets.ORACLE_HOST_IP }} "cd ~/deployment-temp && chmod +x deployment/github-actions-update.sh && ./deployment/github-actions-update.sh && rm -rf ~/deployment-temp"
